name: lesgou
description: To do app.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.4
  fluttertoast: ^8.1.2
  modal_progress_hud_nsn: ^0.3.0
  dot_navigation_bar: ^1.0.1+4
  calendar_timeline: ^1.1.0
  syncfusion_flutter_calendar: ^20.4.48
  cloud_firestore: ^4.3.1
  flutter_datetime_picker: ^1.5.1
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/background_img.png

  fonts:
    - family: OrelegaOne
      fonts:
        - asset: fonts/OrelegaOne-Regular.ttf
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf
          weight: 700